name: Verify MR

on:
  pull_request: {}

jobs:
  build-mr:
    name: Build Container Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: false
          build-args: |
            RUNNER_VERSION=2.317.0
